@startuml

class Bill {
   private int billID;
     private int userId;
     private double totalAmount;
     private List<Product> products;
}

class User {

    private int userId;
     private String firstName;
     private String lastName;
     private boolean isEmployee;
     private boolean isAffiliate;
     private LocalDate createDate;

}

Bill -- User : > Associated with a User

interface INetPayableAmountService {
   double calculateNetPayableAmount(billId);
}

class Controller{

        double INetPayableAmountService calculateNetPayableAmount(billId);
}

Controller -> INetPayableAmountService


@enduml